plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.drm.downloader'
    compileSdk 34

    defaultConfig {
        applicationId "com.drm.downloader"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

chaquopy {
    defaultConfig {
        version "3.10"
        pip {
            install "pywidevine"
            install "cryptography"
            install "requests"
            install "pycryptodome"
            install "lxml"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    
    implementation 'io.github.junkfood02.youtubedl-android:library:0.18.1'
    implementation 'io.github.junkfood02.youtubedl-android:ffmpeg:0.18.1'
    implementation 'io.github.junkfood02.youtubedl-android:aria2c:0.18.1'
}
